name: nxdesign
description: "A design system for Nxtended apps using Nothing's Design Language"
version: 1.2.0
homepage:

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter.otf
    - family: InterMonoDigits
      fonts:
        - asset: fonts/InterMonoDigits.otf
    - family: LetteraMono
      fonts:
        - asset: fonts/LetteraMono.otf
    - family: SpaceMono
      fonts:
        - asset: fonts/SpaceMono.otf
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk.otf
    - family: NDot
      fonts:
        - asset: fonts/NDot77.otf
    - family: NDotMonoDigits
      fonts:
        - asset: fonts/NDot77MonoDigits.otf
    - family: NType
      fonts:
        - asset: fonts/NType82.otf
    - family: NTypeMonoDigits
      fonts:
        - asset: fonts/NType82MonoDigits.otf
